config/routes.rb
Rails.application.routes.draw do
  get "dogs/index"
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :dogs, only: [:show, :index, :new, :create] do
    resources :bookings, only: [:create]
  end

  resources :bookings, only: [:index] do
    resources :reviews, only: [:new, :create]
  end
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :dog
  belongs_to :user
  has_many :reviews, dependent: :destroy
end

app/models/dog.rb
class Dog < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :bookings


  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  validates :name, :birthday, :size, :breed, :address, presence: true #, :image

  def next_dog
    Dog.where("id > ?", id).first
  end

  def previous_dog
    Dog.where("id < ?", id).last
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :booking
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_dog, only: %i[create]

  def create
    @booking = Booking.new(booking_params)
    @booking.dog = @dog
    @booking.user = current_user
    @booking.save
    redirect_to dog_path(@dog), notice: "Booking confirmed!"
  end

  def index
    @current_bookings = Booking.where(user: current_user, start_date: ..Date.today, end_date: Date.today + 1..)
    @past_bookings = Booking.where(user: current_user, end_date: ..Date.today - 1)
    @future_bookings = Booking.where(user: current_user, start_date: Date.today + 1..)
  end

  private

  def set_dog
    @dog = Dog.find(params[:dog_id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end

end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  def index
    @dogs = Dog.all

    if params[:query]
      @dogs = @dogs.where("breed ILIKE ?", "%#{params[:query]}%")
    end

    @markers = @dogs.geocoded.map do |dog|
      {
        lat: dog.latitude,
        lng: dog.longitude
      }
    end
  end

  def show
    @dog = Dog.find(params[:id])
    @user_booking = Booking.find_by(user: current_user, dog: @dog) if current_user
    @review = Review.new
    @booking = Booking.new
    @review = Review.new
  end

  def new
    @dog = Dog.new
  end

  def create
    @dog = Dog.new(dog_params)
    @dog.user = current_user
    if @dog.save
      redirect_to dog_path(@dog)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def dog_params
    params.require(:dog).permit(:name, :birthday, :size, :breed, :address, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @full_width = true
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @booking = Booking.find(params[:booking_id])
    @review = Review.new(review_params)
    @review.booking = @booking
    @review.user = current_user
    if @review.save
      redirect_to dog_path(@booking.dog)
    else
      render "dogs/show", status: :unprocessable_entity
    end
  end

  def new
    @review = Review.new
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="container my-5">
<h2>Current Bookings</h2>
<% if @current_bookings.present? %>
  <% @current_bookings.each do |booking| %>
    <div class="row justify-content-center my-4">
      <div class="col-6 d-flex justify-content-between align-items-center">
        <%= image_tag "dog.jpg", alt: "Dog", style: "width: 40%", class: "dog-photo" %>
        <div class="d-flex flex-wrap border-bottom border-dark mx-4">
            <div class="d-flex  dog-attribute-index"><h3>name</h3><span><%= booking.dog.name %></span></div>
            <div class="d-flex  dog-attribute-index"><h3>birthday</h3><span><%= booking.dog.birthday %></span></div>
            <div class="d-flex  dog-attribute-index"><h3>size</h3><span><%= booking.dog.size %></span></div>
            <div class="d-flex  dog-attribute-index"><h3>breed</h3><span><%= booking.dog.breed %></span></div>
            <div class="d-flex  dog-attribute-index"><h3>address</h3><span><%= booking.dog.address %></span></div>
        </div>
      </div>
      <div class="col-6 d-flex justify-content-around align-items-center">
          <div class="user-booking-index"><h3>status</h3><span><%= booking.status %></span></div>
          <div class="user-booking-index"><h3>booking start</h3><span><%= booking.start_date.strftime("%d %b %Y") %></span></div>
          <div class="user-booking-index"><h3>booking end</h3><span><%= booking.end_date.strftime("%d %b %Y") %></span></div>
      </div>
    </div>
  <% end %>
<% else %>
  <p> No current bookings  </p>
<% end %>

<h2>Upcoming Bookings</h2>
<% if @future_bookings.present? %>
  <% @future_bookings.each do |booking| %>
    <div class="row justify-content-center my-4">
      <div class="col-6 d-flex justify-content-between align-items-center">
        <%= image_tag "dog.jpg", alt: "Dog", style: "width: 40%", class: "dog-photo" %>
        <div class="d-flex flex-wrap border-bottom border-dark mx-4">
            <div class="d-flex  dog-attribute-index"><h3>name</h3><span><%= booking.dog.name %></span></div>
            <div class="d-flex  dog-attribute-index"><h3>birthday</h3><span><%= booking.dog.birthday %></span></div>
            <div class="d-flex  dog-attribute-index"><h3>size</h3><span><%= booking.dog.size %></span></div>
            <div class="d-flex  dog-attribute-index"><h3>breed</h3><span><%= booking.dog.breed %></span></div>
            <div class="d-flex  dog-attribute-index"><h3>address</h3><span><%= booking.dog.address %></span></div>
        </div>
      </div>
      <div class="col-6 d-flex justify-content-around align-items-center">
          <div class="user-booking-index"><h3>status</h3><span><%= booking.status %></span></div>
          <div class="user-booking-index"><h3>booking start</h3><span><%= booking.start_date.strftime("%d %b %Y") %></span></div>
          <div class="user-booking-index"><h3>booking end</h3><span><%= booking.end_date.strftime("%d %b %Y") %></span></div>
      </div>
    </div>
  <% end %>
<% else %>
  <p> No upcoming bookings  </p>
<% end %>

<h2>Past Bookings</h2>
<% if @past_bookings.present? %>
  <% @past_bookings.each do |booking| %>

    <div class="row justify-content-end my-4">

      <div class="col-6 d-flex justify-content-between align-items-center">
        <%= image_tag "dog.jpg", alt: "Dog", style: "width: 40%", class: "dog-photo" %>
        <div class="d-flex flex-wrap border-bottom border-dark mx-4">
            <div class="d-flex  dog-attribute-index"><h3>name</h3><span><%= booking.dog.name %></span></div>
            <div class="d-flex  dog-attribute-index"><h3>birthday</h3><span><%= booking.dog.birthday %></span></div>
            <div class="d-flex  dog-attribute-index"><h3>size</h3><span><%= booking.dog.size %></span></div>
            <div class="d-flex  dog-attribute-index"><h3>breed</h3><span><%= booking.dog.breed %></span></div>
            <div class="d-flex  dog-attribute-index"><h3>address</h3><span><%= booking.dog.address %></span></div>
        </div>
      </div>

      <div class="col-6 d-flex justify-content-around align-items-top">
          <div class="user-booking-index"><h3>status</h3><span><%= booking.status %></span></div>
          <div class="user-booking-index"><h3>booking start</h3><span><%= booking.start_date.strftime("%d %b %Y") %></span></div>
          <div class="user-booking-index"><h3>booking end</h3><span><%= booking.end_date.strftime("%d %b %Y") %></span></div>
      </div>

      <div class="p-2 col-2">
        <%= link_to "Leave a review!", dog_path(booking.dog), class:"btn btn-info fw-bold" %></div>
      </div>


  <% end %>
<% else %>
  <p> No previous bookings  </p>
<% end %>
</div>

app/views/dogs/index.html.erb
<div class="container mt-3"></div>
  <div class="col-12">
    <h1>Meet the Dogs!</h1>
  </div>
<div class="d-flex">
  <div class="pe-4" style="width: 50%">
    <div class="row">
    </div>
    <div class="row">
      <% @dogs.each do |dog| %>
        <div class="col-md-6 mb-4">
          <div class="smol-card-component">
             <%= cl_image_tag dog.photo.key, class: "smol-card-component-img-top" %>
            <div class="smol-card-component-body">
              <%= link_to "Meet #{dog.name}", dog_path(dog), class:"btn btn-info fw-bold" %>
              <p class="smol-card-component-text mt-3 mb-0"><i class="fa-solid fa-dog"></i> <%= dog.breed %></p>
              <p class="smol-card-component-text"><i class="fa-solid fa-location-dot"></i> <%= dog.address %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
    <div class="sticky-map" style="position: sticky !important; width: 50%; height: 100vh;"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
</div>
</div>

app/views/dogs/new.html.erb
<div class="d-flex justify-content-center my-3">
  <%= simple_form_for(@dog) do |d| %>
    <%= d.input :name %>
    <%= d.input :birthday %>
    <%= d.input :size %>
    <%= d.input :breed %>
    <%= d.input :address %>
    <%= d.input :photo, as: :file, label: "Picture of your Dog" %>
    <%= d.submit "Add Your Dog!" %>
  <% end %>
</div>

app/views/dogs/show.html.erb
<div class="container justify-content-center my-5" >
  <div class="row justify-content-center">
    <div class="col-8">
      <div class="d-flex justify-content-between align-items-center dog-header">
        <h2><%= @dog.name %></h2>
        <div class="d-flex justify-content-end dog-nav-links">
          <%= link_to "Back to Gallery", dogs_index_path %>
          <%= link_to "Previous", dog_path(@dog.previous_dog) if @dog.previous_dog %>
          <%= link_to "Next", dog_path(@dog.next_dog) if @dog.next_dog %>
        </div>
      </div>

      <%= cl_image_tag @dog.photo.key, style: "width: 100%", class: "mb-5 mt-3 dog-photo" %>

      <div class="d-flex flex-wrap border-bottom border-dark">
        <div class="d-flex  dog-attribute"><h3>BIRTHDAY</h3><span><%= @dog.birthday %></span></div>
        <div class="d-flex  dog-attribute"><h3>SIZE</h3><span><%= @dog.size %></span></div>
        <div class="d-flex  dog-attribute"><h3>BREED</h3><span><%= @dog.breed %></span></div>
        <div class="d-flex  dog-attribute"><h3>ADDRESS</h3><span><%= @dog.address %></span></div>
      </div>
      <div class="d-flex flex-column my-5 dog-review">
        <% @dog.reviews.each do |review| %>
          <div>
            <h4><%= review.user.first_name %> <%= review.user.last_name %></h4>
            <div>
              <% review.rating.times do  %>
                <i class="fa-solid fa-paw"></i>
              <% end %>
            </div>
            <p>
              <%= review.comment %>
            </p>
          </div>
        <% end %>
      </div>
    </div>

    <div class="col-4">
      <%= simple_form_for [@dog, @booking] do |f| %>
        <%= f.input :start_date %>
        <%= f.input :end_date %>
        <%= f.submit "Submit booking", class: "btn btn-info border-radius" %>
      <% end %>
    </div>
  </div>
</div>

<% if @user_booking %>
  <%= simple_form_for([@user_booking, @review]) do |f| %>
    <%= f.input :rating, collection: 1..5 %>
    <%= f.input :comment %>
    <%= f.button :submit %>
  <% end %>
<% end %>

<%= link_to "Back to all dogs", dogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BarkBuddy</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <div class="<%="container" unless @full_width%>">
      <%= yield %>
    </div>
    <%= render "shared/flashes" %>
    <%= render "shared/footer" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/pages/home.html.erb
<div>
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1568393691622-c7ba131d63b4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8ZG9ncyUyMHBsYXlpbmd8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60);">
    <div class="container">
      <h1>BarkBuddy helps your little buddy find a babysitter while you're away!</h1>
      <p>Travel the world in peace knowing your peluche is being taken care of.</p>
    </div>
  </div>
  <div class="container">
    <div class="justify-content-between my-5 text-center container-info">
      <h2 class="my-3">Why should you use BarkBuddy?</h2>
      <div class="d-flex justify-content-between my-3">
        <div class="my-3 col-lg-4">
          <h3>Community</h3>
          <p>Join similar minded people in your local area who are part of BarkBuddy</p>
        </div>
        <div class="my-3 col-lg-4">
          <h3>Safety</h3>
          <p>Know that you're using a platform where dog-sitters are vetted and have passed a safety check</p>
        </div>
        <div class="my-3 col-lg-4">
          <h3>Good Vibes</h3>
          <p>By being part of BarkBuddy, know that you're sharing the love of taking care of dogs</p>
        </div>
      </div>
      <div class="justify-content-center">
        <%= link_to "Meet the dogs in your area!", dogs_index_path, class: "btn btn-info my-3 col-sm-3" %>
      </div>
    </div>
    <div class="cards">
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1611003228941-98852ba62227?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmFieSUyMGRvZ3xlbnwwfHwwfHx8MA%3D%3D&w=1000&q=80)">
        Rupert
      </div>

      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2017/11/20183655/German-Pinscher-standing-near-a-lake.jpg)">
        Rufus
      </div>

      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://hips.hearstapps.com/hmg-prod/images/dog-puppy-on-garden-royalty-free-image-1586966191.jpg?crop=1xw:0.74975xh;center,top&resize=1200:*)">
        Mutley
      </div>

      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTAAKNz1-J7ZuylwM9AJ7wWztDXXmSWvirbWQ&usqp=CAU)">
        Duke
      </div>

      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://media.istockphoto.com/id/1388796467/photo/adorable-young-bichon-frise-puppy-walks-around-the-sunny-spring-lawn-active-cute-puppy.jpg?s=612x612&w=0&k=20&c=HxqL0MxV-whnGOU_tgnTYC9Ajj0m77iorASymQqYQ1w=)">
        Binny
      </div>

      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ39E-qztdLhp_9_67M1PwGi0cVJZiewthBAA&usqp=CAU)">
        Smokey
      </div>

      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTWu5meYDlGASCjdmSLMYSL_cM8LdwLUgcfA&usqp=CAU)">
        Snowball
      </div>

      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://hips.hearstapps.com/hmg-prod/images/lifestyle-bestdogbreeds-1577128927.png?crop=1.00xw:1.00xh;0,0&resize=1200:*)">
        Buddy
      </div>

      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQo8EI_ZzLQDfMkZ5mLQaQLfUwb_dgPDK8PKQ&usqp=CAU)">
        Rocky
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
    <div class="footer-links">
      <a href="#"><i class="fab fa-github"></i></a>
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
      <a href="#"><i class="fab fa-linkedin"></i></a>
    </div>
    <div class="footer-copyright">
      @BarkBuddy 2023
      <strong>This site uses cookies</strong>
    </div>
  </div>

app/views/shared/_navbar.html.erb
<div class="navbar sticky-top navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <div class="d-flex justify-content-start align-items-center">
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTDBZWCALotd8NtIPCKubDqC95h0RG5wnnKcg&usqp=CAU" %>
      <% end %>
      <h1>BarkBuddy</h1>
    </div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <%= form_with url: dogs_index_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
                          params[:query],
                          class: "form-control rounded",
                          placeholder: "Search buddies..." %>
      <%= button_tag type: 'submit', name: "", class: "btn btn-secondary" do %>
        <i class="fas fa-search"></i>
      <% end %>
    <% end %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My Bookings", bookings_path , class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://scontent-ams4-1.xx.fbcdn.net/v/t39.30808-6/289462788_7699038730138159_3212458452925632917_n.jpg?_nc_cat=102&ccb=1-7&_nc_sid=09cbfe&_nc_ohc=J1oHvSJQApkAX9rgfSG&_nc_ht=scontent-ams4-1.xx&oh=00_AfDjW8V3C5NHskyjaWPqFHrXxsdIuQBeVQOyjynTz3decg&oe=647F397A", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Your Profile", "#", class: "dropdown-item" %>
              <%= link_to "Add Your Dog", new_dog_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>